[theme]
base = "dark"

primaryColor = "#00D4FF"            # bleu cyan (boutons, sliders, accents)
backgroundColor = "#0B0F14"         # fond principal tr√®s sombre
secondaryBackgroundColor = "#131A23" # cartes, sidebar, blocs
textColor = "#E6EDF3"               # texte clair, lisible

font = "sans serif"

